name: 'Recce Cloud CI/CD Action'

description: 'A GitHub Action to integrate Recce Cloud CI/CD from your GitHub repository (TypeScript version).'

author: 'Recce Team'

branding:
  icon: 'upload-cloud'
  color: 'orange'

inputs:
  dbt_target_path:
    description: 'The path to the DBT target directory containing manifest.json and catalog.json (default: target).'
    required: true
    default: 'target'

  base_branch:
    description: 'The base branch for the deployment (default: main).'
    required: false
    default: 'main'

  api_host:
    description: 'The Recce Cloud API host URL.'
    required: false
    default: 'https://cloud.datarecce.io'

  web_host:
    description: 'The Recce Cloud web host URL.'
    required: false
    default: 'https://cloud.datarecce.io'

  github_token:
    description: 'GitHub token for authentication (defaults to github.token if not provided).'
    required: false

outputs:
  session_id:
    description: 'The Recce Cloud session ID for the uploaded artifacts'

runs:
  using: 'node20'
  main: 'dist/index.js'
